name: Build & Deploy Backend to GKE

on:
  push:
    branches: ["main"]

env:
  PROJECT_ID: kxnwork
  REGION: us
  REPO_NAME: backend-repo
  IMAGE: us-docker.pkg.dev/kxnwork/backend-repo/backend:latest
  CLUSTER: backend-gke
  ZONE: us-central1-c

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write     # IMPORTANT for OIDC
      contents: read

    steps:
    - name: Checkout source
      uses: actions/checkout@v4

    # ----------------------
    # OIDC Authentication
    # ----------------------
    - name: Authenticate to Google Cloud using OIDC
      uses: google-github-actions/auth@v2
      with:
        workload_identity_provider: "projects/382207431122/locations/global/workloadIdentityPools/github-pool-priii/providers/github-provider-priii"
        service_account: "github-deployer-priii@kxnwork.iam.gserviceaccount.com"

    - name: Set up gcloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: kxnwork

    - name: Configure Docker for Artifact Registry
      run: gcloud auth configure-docker us-docker.pkg.dev

    - name: Build & Push Docker image
      run: |
        docker build -t $IMAGE ./backend
        docker push $IMAGE

    - name: Get GKE credentials
      run: gcloud container clusters get-credentials $CLUSTER --zone $ZONE --project $PROJECT_ID

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/backend backend=$IMAGE
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml
